#!/bin/bash
### BEGIN INIT INFO
# Provides:       pymavlink_startup
# Required-Start: $network $remote_fs $syslog
# Required-Stop:  $network $remote_fs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    pymavlink
### END INIT INFO

sudo pigpiod
export MAVLINK20="1"
cd /home/pi/Desktop/GACompanionComp/log/

name_log=log
if [[ -e $name_log ]] ; then
    i=0
    while [[ -e $name_log-$i ]] ; do
        let i++
    done
    name_log=$name_log-$i
fi
name_err=err
if [[ -e $name_err ]] ; then
    i=0
    while [[ -e $name_err-$i ]] ; do
        let i++
    done
    name_err=$name_err-$i
fi

/home/pi/Desktop/companionComp/bin/python3 /home/pi/Desktop/GACompanionComp/pymavlink_main.py --vehicle GA3A > "$name_log" 2>"$name_err" &

exit 0
